# Version de la syntaxe Docker Compose
version: '3.8'

# Définition de nos services (conteneurs)
services:
  # On définit un service qu'on nomme 'mongo'
  mongo:
    # On utilise l'image officielle de MongoDB
    image: mongo:latest
    # Nom du conteneur pour le retrouver facilement
    container_name: helha_web3_mongo
    # On fait le lien entre le port de notre machine (gauche) et celui du conteneur (droite)
    # Pour que notre backend sur localhost:XXXX puisse parler à la DB sur localhost:27017
    ports:
      - "27017:27017"
    # Variables d'environnement pour configurer MongoDB au premier lancement
    environment:
      # C'est l'utilisateur "root" pour l'administration de la base
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    # On crée un volume pour que les données persistent même si on supprime le conteneur
    # Le dossier 'mongo-data' sera créé sur notre machine et synchronisé avec '/data/db' dans le conteneur
    volumes:
      - ./mongo-data:/data/db